# Generated by Django 4.2.19 on 2025-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=256, verbose_name='productId')),
                ('cleanName', models.CharField(max_length=256, verbose_name='cleanname')),
                ('imageURL', models.CharField(max_length=256, verbose_name='imageUrl')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
                ('lowPrice', models.FloatField(verbose_name='lowPrice')),
                ('midPrice', models.FloatField(verbose_name='midPrice')),
                ('highPrice', models.FloatField(verbose_name='highPrice')),
                ('marketPrice', models.FloatField(verbose_name='marketPrice')),
                ('subType', models.CharField(max_length=256, verbose_name='subTypeName')),
                ('extNumber', models.CharField(max_length=256, verbose_name='extNumber')),
                ('extDescription', models.CharField(max_length=1024, verbose_name='extDescription')),
            ],
        ),
    ]
