# Generated by Django 4.2.19 on 2025-03-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='imageURL',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='productID',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='subType',
            new_name='subTypeName',
        ),
    ]
