# Generated by Django 4.2.19 on 2025-03-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_imageurl_cards_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='extDescription',
        ),
    ]
