# Generated by Django 4.2.19 on 2025-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_cards_extdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='url',
            field=models.ImageField(upload_to='img', verbose_name='url'),
        ),
    ]
