# Generated by Django 4.2.19 on 2025-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_cards_imageurl_alter_cards_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='imageUrl',
            field=models.URLField(max_length=256, verbose_name='imageUrl'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='url',
            field=models.URLField(max_length=256, verbose_name='url'),
        ),
    ]
