# Generated by Django 4.2.19 on 2025-04-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
