# Generated by Django 4.2.19 on 2025-04-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_cards_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
