# Generated by Django 4.2.20 on 2025-04-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_uploadedimage_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='matched_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.card'),
        ),
    ]
