# Generated by Django 4.2.20 on 2025-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_uploadedimage_matched_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='extDescription',
            field=models.CharField(default='~~~', max_length=1024, verbose_name='extDescription'),
            preserve_default=False,
        ),
    ]
