# Generated by Django 5.1.7 on 2025-04-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_uploadedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
